### ISSUE TITLE
v5-stable, debian-wheezy and newer klog directives

### ISSUE THREAD

**Issue by loli10K** [rsyslog/rsyslog-doc#204]
Hi,
i'm trying to configure rsyslog (v5.8.11) on my wheezy machine to use both `$klogParseKernelTimestamp` and `$klogKeepKernelTimestamp` directives. Unfortunately things don't seem to be working at all.

Running rsyslogd (`rsyslogd -d -n -c5 -f /etc/rsyslog.conf`) shows:

```
2746.072457647:b6fb7000: cfline: '$ModLoad imklog   # provides kernel logging support'
2746.072493935:b6fb7000: Requested to load module 'imklog'
2746.072520308:b6fb7000: loading module '/usr/lib/rsyslog/imklog.so'
2746.073410396:b6fb7000: module of type 0 being loaded.
2746.073459016:b6fb7000: entry point 'isCompatibleWithFeature' not present in module
2746.073492763:b6fb7000: cfline: '$klogParseKernelTimestamp on'
2746.073528927:b6fb7000: Called LogError, msg: invalid or yet-unknown config file command - have you forgotten to load a module?
2746.073851148:b6fb7000: config line NOT successfully processed
2746.073888812:b6fb7000: Called LogError, msg: the last error occured in /etc/rsyslog.conf, line 13:"$klogParseKernelTimestamp on"
2746.073936766:b6fb7000: cfline: '$klogKeepKernelTimestamp off'
2746.073980762:b6fb7000: Called LogError, msg: invalid or yet-unknown config file command - have you forgotten to load a module?
2746.074012092:b6fb7000: config line NOT successfully processed
2746.074032715:b6fb7000: Called LogError, msg: the last error occured in /etc/rsyslog.conf, line 14:"$klogKeepKernelTimestamp off"
```

Reading the docs here http://www.rsyslog.com/doc/v5-stable/configuration/modules/imklog.html both configuration directives seem to be supported.

I downloaded the latest v5 stable from debian archive (`apt-get source rsyslog`) and rsyslog website (`http://www.rsyslog.com/download/stable-download/page/files/download/rsyslog/rsyslog-5.10.1.tar.gz`), grepped through the sources but couldn't find `$klogParseKernelTimestamp` and `$klogKeepKernelTimestamp` directives.

I'm going to trust the sources (and facts) and guess these directives are not supported in v5, but why are they listed in the official docs? Before trying v7 from the wheezy backports i wanted to be really sure i haven't missed something.

**Comment by rgerhards** [comment]
was imklog loaded before these statements were given? I ask because they are from this module.

**Comment by loli10K** [comment]
Yes, i put those 2 directives just after loading the module in my rsyslog.conf:

```
#################
#### MODULES ####
#################

$ModLoad imuxsock # provides support for local system logging
$ModLoad imklog   # provides kernel logging support
$klogParseKernelTimestamp on
$klogKeepKernelTimestamp off
```

also, from the log i posted before the module seems to be loaded successfully:

```
2746.072457647:b6fb7000: cfline: '$ModLoad imklog   # provides kernel logging support'
2746.072493935:b6fb7000: Requested to load module 'imklog'
2746.072520308:b6fb7000: loading module '/usr/lib/rsyslog/imklog.so'
2746.073410396:b6fb7000: module of type 0 being loaded.
2746.073459016:b6fb7000: entry point 'isCompatibleWithFeature' not present in module
```

**Comment by rgerhards** [comment]
Then I guess its a bug in that old version.

**Comment by rgerhards** [comment]
oh, I just notice that you have a 5.8 version, which is even older than the latest 5.10.somewhat v5 version. Maybe it's not present in that even older version ;)

**Comment by loli10K** [comment]
I tried both the latest v5-stable that ships by default with debian wheezy (5.8.11) and the latest from the rsyslog.com website (5.10.1): neither of them seem to support those directives.

My point is, why are those directives listed in the v5-stable docs if they're not even in the source code of the latest (5.10.1) available from the official website?

**Comment by rgerhards** [comment]
I checked git. It was intended to be part of 5.10.2, which obviously is the state of the doc. 5.10.2 was never released. Note that v5 is nearly 6 years old and no longer project supported for ages.

**Comment by loli10K** [comment]
So the docs for v5-stable on the official website list features that are actually supported only if you build it from source; but don't use the source tarball from the official website because the code is outdated. Welp.

I just cloned the github repo, the latest v5 tag is v5.9.7 which does not contain support for those features. I couldn't even find a v5 branch. I guess you're not referring to the v5-stable on the github repo. I'm going to stick to the latest v7 from wheezy backports.

This is one of those times that actually RTFM doesn't help, like, at all.

**Comment by rgerhards** [comment]
Well, as I said - **v5 is loooooong dead**. And I now remember that we officially ditched the branch quite some years ago as the result of some mailing list discussions. I pulled v5-stable from my copy. The project supported version is v8.15.0.

**Comment by loli10K** [comment]
I should clarify: my intention was not to bitch about this great project or to be rude in any way, and i'm actually grateful you took the time to respond on sunday.

It's just, debian wheezy and rhel6 are still out there and some of us have to keep "supporting" them, in some way or another. Maybe just update the download link on the website or the v5-stable docs for the next sysadmin trying to get those klog features working on older distros.

**Comment by rgerhards** [comment]
Yeah, but the problem is that it is long dead and there are so many things to do. So it's not smart to spent time on things that we do no longer care about. Look at it that way: the download link is correct (it contains the latest v5 version and, btw, it also contains the doc that goes along with exactly that version). Fixing the doc on the web site bases on an automatted process and we probably need 2..4 hours to get things updated.

**Comment by loli10K** [comment]
rhel6 does indeed ship the docs in a single package alongside the binaries, wheezy unfortunately does not: there's a separate `rsyslog-doc` package which i don't install because it's much easier to read the docs online than from a headless server.

In other news i just installed v7 from wheezy backports and it's working like a charm.

**Comment by davidelang** [comment]
This is a problem with the "Enterprise" or "Long Term Support" versions of distros. They promise the users that they will be supported for years, long after the upstream projects stop support of those versions.

The "correct" answer is to point the users who need support at their distros who promised the support, but people don't like that answer for some reason :-)

It's especially frustrating for those of us in the upstream projects to have someone say (usually over several messages) "I want you to support this ancient version because I can't get an answer from the distro, but I refuse to upgrade to a newer version because it will break support from my distro"

The legacy syntax info is still in the latest docs, just down at the bottom. There are issues (like this one) where the issue is 'what version was this feature introduced in', and for the older features, this isn't always clear, but it's really not worth the effort to go back to the old versions to try and fix it. As noted earlier, the old versions shipped with old versions of the docs, trying to have every single version of the docs available on the website is not practical.

Also, remember that this is all available in the git repo, so you can go back to any old version on your own.

**Comment by trixpan** [comment]
It is worth pointing that RedHat supports rsyslog7 on RHEL6 (albeit the install can be challenging due to the way rpm and yum handle dependencies (you better of kickstart with the new version that trying to push it after).

Sources:
https://access.redhat.com/solutions/282663
