### ISSUE TITLE
building from source taball is broken

### ISSUE THREAD

**Issue by mbiebl** [rsyslog/rsyslog-doc#504]
Since commit de28b1a5d2f9c5b606ca4065354f1578f7e9cf61 building the documentation from the source tarball is broken, as the source tarball does not have a .git directory:
```
Running Sphinx v1.6.6
fatal: Not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

Configuration error:
There is a programable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/config.py", line 157, in __init__
    execfile_(filename, config)
  File "/usr/lib/python3/dist-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "conf.py", line 69, in <module>
    git_tag_output = subprocess.check_output(['git', 'tag', '--list', "v*"]).decode("utf-8").strip()
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'tag', '--list', 'v*']' returned non-zero exit status 128.
```

**Comment by mbiebl** [comment]
cc @deoren

**Comment by mbiebl** [comment]
btw, it's not a good idea to use the current day in the release version like this

release = "{}-{}-{}".format(version, TODAY, commit)

The release version should not changed depending on whether I built the docs yesterday or today.

**Comment by mbiebl** [comment]
See https://reproducible-builds.org/docs/timestamps/ why embedding timestamps is a bad idea

**Comment by deoren** [comment]
@mbiebl 

Thanks for the report and sorry for the trouble you experienced.

I'm actively researching and drafting a detailed response; I will respond back once I've got the details together.

**Comment by mbiebl** [comment]
fwiw, I applied this patch for now in Debian: https://salsa.debian.org/debian/rsyslog-doc/commit/fdb2275fdcf1252af969cc2a2908ce019595686f

Manually updating the version number is obviously not a proper fix, so I hope we can find a solution which works for everyone.

**Comment by deoren** [comment]
@mbiebl What is your build process for producing the release tarball?

**Comment by mbiebl** [comment]
@deoren I'm not producing a release tarball. I'm using the one provided at http://www.rsyslog.com/downloads/download-v8-stable/

What I do though is to rebuild the documentation from source as part of the build process, i.e. I don't ship the pre-generated html files.

**Comment by deoren** [comment]
@mbiebl Thanks for the details. What you've described is entirely logical and (as you're well aware) is a valid expectation on your part. I'll make sure to cover this point specifically in my longer response.

**Comment by mbiebl** [comment]
Just to clarify, I downloaded http://www.rsyslog.com/files/download/rsyslog/rsyslog-doc-8.32.0.tar.gz for the latest update.

**Comment by deoren** [comment]
@mbiebl I'll post-pone my detailed response for later in an effort to go ahead and get this pushed through sooner rather than later.

**Comment by deoren** [comment]
> @mbiebl: Since commit de28b1a building the documentation from the source tarball is broken, as the source tarball does not have a .git directory

First of all, my apologies again for the trouble.

PR #505 reverts to the prior behavior of using a static version number and drops the Git dependency. I plan to return to dynamic versioning, but in a different way than before so that building from tarball sources remains reliable for downstream package maintainers.

> @mbiebl: btw, it's not a good idea to use the current day in the release version like this
>
> 
> ```release = "{}-{}-{}".format(version, TODAY, commit)```
> 
> The release version should not change depending on whether I built the docs yesterday or today.

See below.

> @mbiebl: See https://reproducible-builds.org/docs/timestamps/ why embedding timestamps is a bad idea

The modifications to the release and version strings were intended to be verbose (stable version +1, date, commit hash) for "dev" builds and then have a build script handle overriding both of those values with appropriate "release" build details that omitted everything except for the new version details:

Ex: 
> - `version = 8.32`
> - `release = 8.32.0`

This would have resulted in a tarball with the correct release version info in the HTML files, but as you have inferred, building the source files from the tarball would have been treated as a "dev" build and not resulted in "release" build docs (like the output HTML files included in the tarball).

In short, I really dropped the ball working out the details with @rgerhards to establish a stable docs release process. This is entirely my fault.

Going forward (PR #505), the logic will be reversed and the Git dependency dropped so that release/stable builds work as expected directly from tarball sources.

To support both that goal and dynamic builds, I plan to update the process on our end so that the `source/conf.py` file is dynamically updated with static version numbers as part of the tarball generation process. This should remove the need to manually touch `source/conf.py` or specify the specific version when building the release tarball (doc sources, output HTML).

If you like, I will loop you in on the changes prior to having them merged so you will be aware of them and can offer feedback.

**Comment by deoren** [comment]
@mbiebl PR #505 has been merged. I suspect that regenerating the tarball and creating a new tag would probably not be a popular move, so I went ahead and updated the static version/release strings to reflect the upcoming 8.33.0 release. That way if the changes I'm working on in another PR are not stabilized the release tarball creation process should be stable.

Sorry again for the trouble and thank you for the detailed feedback.

I'll go ahead and close this, but please sound off if I've forgotten anything.
